flags: {}
packages:
- servant-auth
- servant-auth-server
- servant-auth-client
- servant-auth-docs
- servant-auth-swagger
extra-deps:
- aeson-1.2.2.0
- bytestring-builder-0.10.8.1.0
- call-stack-0.1.0
- fast-logger-2.4.7
- hspec-2.4.4
- hspec-core-2.4.4
- hspec-discover-2.4.4
- hspec-expectations-0.8.2
- http-api-data-0.3.7.1
- jose-0.6.0.3
- mmorph-1.0.9
- servant-0.11
- servant-client-0.11
- servant-docs-0.11
- servant-server-0.11
- unix-time-0.3.7
- wai-extra-3.0.19
- warp-3.2.9
resolver: lts-9.6
