name:                servant-auth
version:             0.2.7.0
synopsis:            Authentication combinators for servant
description:         |
    This package provides an @Auth@ combinator for 'servant'. This combinator
    allows using different authentication schemes in a straightforward way,
    and possibly in conjunction with one another.

    'servant-auth' additionally provides concrete authentication schemes, such
    as Basic Access Authentication, JSON Web Tokens, and Cookies.

    For more details on how to use this, see the <http://github.com/plow-technologies/servant-auth#readme README>.
homepage:            http://github.com/plow-technologies/servant-auth#readme
license:             BSD3
license-file:        LICENSE
author:              Julian K. Arni
maintainer:          jkarni@gmail.com
category:            Web, Servant, Authentication
copyright:           (c) Julian K. Arni
github:              plow-technologies/servant-auth
tested-with:         GHC == 7.10.2, GHC == 8.0.1, GHC == 8.2.1

extra-source-files:
  - package.yaml

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 4.11

default-extensions:
  - AutoDeriveTypeable
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - KindSignatures
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators

library:
  source-dirs:      src
  other-modules:    []

tests:
  spec:
    main:            Spec.hs
    other-modules:   []
    source-dirs:     test
    dependencies:
      - servant-auth
      - hspec > 2 && < 3
      - QuickCheck >= 2.8 && < 2.11

  doctest:
    main:            Doctest.hs
    other-modules:   []
    source-dirs:     test
    dependencies:
      - doctest >= 0.9 && < 0.14
      - Glob >= 0.7 && < 0.10
      - yaml == 0.8.*
