name:                servant-auth-server
version:             0.2.0.0
synopsis:            servant-server/servant-auth compatibility
description:         |
    This package provides the required instances for using the @Auth@ combinator
    in your 'servant' server.

    Both cookie- and token- (REST API) based authentication is provided.

    For a quick overview of the usage, see the <http://github.com/plow-technologies/servant-auth#readme README>.
homepage:            http://github.com/plow-technologies/servant-auth#readme
license:             BSD3
license-file:        LICENSE
author:              Julian K. Arni
maintainer:          jkarni@gmail.com
category:            Web, Servant, Authentication
copyright:           (c) Julian K. Arni
github:              plow-technologies/servant-auth
tested-with:         GHC == 7.10.2, GHC == 8.0.1

ghc-options: -Wall

dependencies:
  - base                    >= 4.7  && < 4.10
  - text                    >= 1    && < 2
  - servant-auth            == 0.2.*
  # We have an orphan instance for SetCookie, so we need to be careful about upper bounds.
  - cookie                  >= 0.4  && < 0.4.2.2
  - wai                     >= 3.2  && < 3.3
  - mtl                     >= 2.2  && < 2.3
  - bytestring              >= 0.10 && < 0.11
  - bytestring-conversion   >= 0.3  && < 0.4
  - case-insensitive        >= 1.2  && < 1.3
  - jose                    >= 0.5  && < 0.6
  - monad-time              >= 0.2  && < 0.3
  - time                    >= 1.5  && < 1.7
  - servant-server          >= 0.7  && < 0.10
  - base64-bytestring       >= 1    && < 2
  - blaze-builder           >= 0.4  && < 0.5
  - unordered-containers    >= 0.2  && < 0.3
  - aeson                   >= 0.11 && < 2
  - lens                    >= 4    && < 5
  - entropy                 >= 0.3  && < 0.4
  - crypto-api              >= 0.13 && < 0.14
  - data-default-class      >= 0.0  && < 0.2
  - http-api-data           >= 0.2  && < 0.4
  - http-types              >= 0.9  && < 0.10


default-extensions:
  - AutoDeriveTypeable
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - KindSignatures
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators

library:
  source-dirs:      src
  other-modules:    []

tests:
  spec:
    main:            Spec.hs
    source-dirs:     test
    dependencies:
      - servant-auth-server
      - hspec > 2 && < 3
      - QuickCheck >= 2.8 && < 2.9
      - aeson
      - lens-aeson
      - warp
      - wreq
      - http-types
      - http-client

executables:
  readme:
    main:            README.lhs
    source-dirs:     executables
    ghc-options:     -pgmL markdown-unlit
    dependencies:
      - servant-auth
      - servant-auth-server
      - servant-server  >= 0.8 && < 0.10
      - warp
      - markdown-unlit
      - transformers
